version: '3'
services:
  node-app:
    build: .
    container_name: my-node-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
